// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZOKyURSR7o6HKFdqy45rPtCW-a0VbEQc',
    appId: '1:994662502353:web:b75a40a77c26344bf41af0',
    messagingSenderId: '994662502353',
    projectId: 'ecommerce-7084a',
    authDomain: 'ecommerce-7084a.firebaseapp.com',
    storageBucket: 'ecommerce-7084a.firebasestorage.app',
    measurementId: 'G-N5K817EG8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPfgkeQsGHSMqzb4Nr9VQDyI0Ov0Y9s0',
    appId: '1:994662502353:android:5a506d5be20ab62bf41af0',
    messagingSenderId: '994662502353',
    projectId: 'ecommerce-7084a',
    storageBucket: 'ecommerce-7084a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt9O3b4wpZE2NpEuui9unlBlaN1y23q64',
    appId: '1:994662502353:ios:1437eb85695315f2f41af0',
    messagingSenderId: '994662502353',
    projectId: 'ecommerce-7084a',
    storageBucket: 'ecommerce-7084a.firebasestorage.app',
    iosBundleId: 'com.example.testProjEco',
  );
}
